---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf-server
  labels:
    app: iperf-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf-server
  template:
    metadata:
      labels:
        app: iperf-server
    spec:
      containers:
      - name: iperf-server
        image: networkstatic/iperf3
        args:
          - -s
        ports:
          - containerPort: 5201
