---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: iperf-client-local
  name: iperf-client-local
spec:
  parallelism: 1
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: iperf-client-local
    spec:
      restartPolicy: Never
      containers:
        - name: iperf-server
          image: networkstatic/iperf3
          args:
            - -c
            - iperf-server
            - --time=10
            - --parallel=16
