apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dbox
  labels:
    app: dbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbox
  serviceName: dbox
  template:
    metadata:
      labels:
        app: dbox
    spec:
      #nodeSelector:
      #  kubernetes.io/hostname: some-node
      containers:
      - name: dbox
        image: adgit/debug:20250204-v1
        args:
        - -c
        - "trap : TERM INT; sleep infinity & wait"
        command:
          - /bin/sh
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 1000m
            memory: 1Gi
      dnsPolicy: Default
      tolerations:
        - key: kubernetes.io/arch
          operator: Equal
          value: arm64
          effect: NoSchedule
