apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dbox
  labels:
    app: dbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbox
  serviceName: dbox
  template:
    metadata:
      labels:
        app: dbox
    spec:
      containers:
      - name: dbox
        image: adgit/ioperf:2024-05-17.rc2
        args:
        - -c
        - "trap : TERM INT; sleep infinity & wait"
        command:
          - /bin/bash
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 1000m
            memory: 1Gi
      dnsConfig:
        options:
        - name: ndots
          value: "1"
