apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nb-dbox
  labels:
    app: nb-dbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nb-dbox
  serviceName: nb-dbox
  template:
    metadata:
      labels:
        app: nb-dbox
    spec:
      #hostPID: true
      #hostIPC: true
      #hostNetwork: true
      #nodeSelector:
      #  kubernetes.io/hostname: gke-infra-mgmt-4a56a4-t2a-standard-4-864584c5-ccmr
      containers:
      - name: dbox
        image: adgit/debug:20250204-v1
        args:
        - -c
        - "trap : TERM INT; sleep infinity & wait"
        command:
          - /bin/sh
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        securityContext:
          privileged: true
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      tolerations:
      - effect: NoSchedule
        key: kubernetes.io/arch
        operator: Equal
        value: arm64

