apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: super-dbox
  labels:
    app: super-dbox
spec:
  selector:
    matchLabels:
      app: super-dbox
  template:
    metadata:
      labels:
        app: super-dbox
    spec:
      hostPID: true
      hostIPC: true
      hostNetwork: true
      containers:
      - name: dbox
        image: adgit/debug:20250204-v1
        args:
        - -c
        - "trap : TERM INT; sleep infinity & wait"
        command:
          - /bin/bash
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /dev
          name: dev
        - mountPath: /sys/dev
          name: sys-dev
        - mountPath: /mnt
          name: mnt
          mountPropagation: Bidirectional
        - mountPath: /var/run
          name: var-run
        - mountPath: /ttt
          name: ttt
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      volumes:
      - hostPath:
          path: /dev
          type: Directory
        name: dev
      - hostPath:
          path: /sys/dev
          type: Directory
        name: sys-dev
      - hostPath:
          path: /mnt
          type: Directory
        name: mnt
      - hostPath:
          path: /var/run
          type: Directory
        name: var-run
      - hostPath:
          path: /etc
          type: Directory
        name: ttt
