{{- $allFolders := list }}
{{- range $path, $_ :=  .Files.Glob  "files/dashboards/**.json" }}
{{- $d := splitList "/" (trimPrefix "files/dashboards/" (dir $path)) }}

{{- range $id, $f := $d }}
{{- $folderTitle := $f }}
{{- $folder := join "-" $d | lower }}

{{- if not (has $folder $allFolders) }}
{{- $allFolders = append $allFolders $folder }}
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: {{ $folder }}
spec:
  title: {{ $folderTitle }}
  {{- if gt $id 0 }}
  parentFolderRef: {{ index $d (sub $id 1) | lower }}
  {{- end }}
  instanceSelector:
    matchLabels:
      grafana-instance: "default"
{{- end }}
{{- end }}
{{- end }}
