{{- $allFolders := list }}
{{- $defaults := .Values.grafanaFolders.defaults }}
{{- $overrides := .Values.grafanaFolders.overrides }}

{{- range $path, $_ :=  .Files.Glob  "files/dashboards/**.json" }}
{{- $d := splitList "/" (trimPrefix "files/dashboards/" (dir $path)) }}

{{- $curPath := list }}
{{- $prevPath := list }}

{{- range $id, $f := $d }}

{{- $prevPath = $curPath }}
{{- $curPath = append $curPath $f }}

{{- $folderTitle := $f }}
{{- $folder := join "-" $curPath | lower }}

{{- if not (has $folder $allFolders) }}
{{- $allFolders = append $allFolders $folder }}

{{- $spec := deepCopy $defaults | merge (get $overrides $folder | default dict) }}
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: {{ $folder }}
spec:
  title: {{ $folderTitle }}
  {{- if gt $id 0 }}
  parentFolderRef: {{ join "-" $prevPath | lower  }}
  {{- end }}
  {{- with $spec}}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
