{{- $allFolders := list }}
{{- $allPaths := list }}
{{- $defaults := .Values.grafanaFolders.specDefaults }}
{{- $overrides := .Values.grafanaFolders.specOverrides }}

{{- range $path, $_ := .Files.Glob "files/dashboards/**.json" }}
{{- $p := trimPrefix "files/dashboards/" (dir $path) }}
{{- $allPaths = append $allPaths $p }}
{{- end }}

{{- range $path, $_ := .Files.Glob "files/resources/**/alertrules/*.yaml" }}
{{- $p := trimPrefix "files/resources/" (dir $path) }}
{{- $allPaths = append $allPaths $p }}
{{- end }}

{{- range $_, $path := $allPaths }}
{{- $d := splitList "/" $path }}
{{- $curPath := list }}
{{- $prevPath := list }}

{{- range $id, $f := $d }}

{{- $prevPath = $curPath }}
{{- $curPath = append $curPath $f }}

{{- $folderTitle := $f }}
{{- $folder := join "-" $curPath | lower }}

{{- if not (has $folder $allFolders) }}
{{- $allFolders = append $allFolders $folder }}

{{- $spec := deepCopy $defaults | merge (get $overrides $folder | default dict) }}
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: {{ $folder }}
spec:
  title: {{ $folderTitle }}
  {{- if gt $id 0 }}
  parentFolderRef: {{ join "-" $prevPath | lower  }}
  {{- end }}
  {{- with $spec}}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
