---
kind: Service
apiVersion: v1
metadata:
  name: grpc-hello
  annotations:
    external-dns.alpha.kubernetes.io/hostname: grpc-hello.api.stage.icn.global
    external-dns.alpha.kubernetes.io/target: api.stage.icn.global
  labels:
    app: grpc-hello
spec:
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  selector:
    app: grpc-hello
  type: ClusterIP
