# Default values for test-dynamic-file-structure.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Parameters for GrafanaDashboards
grafanaDashboards:

  # Default spec to be applied to all GrafanaDashboard resources
  defaults:
    resyncPeriod: 60s
    instanceSelector:
      matchLabels:
        grafana-instance: "default"

  # Customization via overrides (deep merge)
  overrides:
    # Custom resync period for dashboard with name "three-one"
    three-one:
      resyncPeriod: 90s

# Parameters for GrafanaFolders
grafanaFolders:

  # Default spec to be applied to all GrafanaFolders resources
  defaults:
    instanceSelector:
      matchLabels:
        grafana-instance: "default"

  # Customization via overrides (deep merge)
  overrides:
    # Custom permissions for folder named "production-services-folderthree"
    production-services-folderthree:
      permissions: |
        {
          "items": [
            {
              "role": "Viewer",
              "permission": 2
            },
            {
              "role": "Editor",
              "permission": 2
            }
          ]
        }
